# Project identification
sonar.projectKey=LasMinruk_user-service
sonar.organization=lasminruk

# Project info
sonar.projectName=User Service
sonar.projectVersion=1.0

# Source code location
sonar.sources=src
sonar.exclusions=node_modules/**,**/*.test.js

# Language
sonar.language=js
sonar.sourceEncoding=UTF-8

